# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfprovidercheck < Formula
  desc "Censor Terraform Providers"
  homepage "https://github.com/suzuki-shunsuke/tfprovidercheck"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.4/tfprovidercheck_darwin_amd64.tar.gz"
      sha256 "97b168b08b02b9e00757a2bea94755cfbef753307d4204ff884ed7763e229d58"

      def install
        bin.install "tfprovidercheck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.4/tfprovidercheck_darwin_arm64.tar.gz"
      sha256 "d9b434ddcf67598660372c8af5fc8b9dbde20cebdc5c1971af75ddcf0aee42e3"

      def install
        bin.install "tfprovidercheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.4/tfprovidercheck_linux_amd64.tar.gz"
        sha256 "0adf02dcb8ca9ad07986f880347ebc348a73b850d8b8b8477b7fa5d5147c0b61"

        def install
          bin.install "tfprovidercheck"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.4/tfprovidercheck_linux_arm64.tar.gz"
        sha256 "fb84129d9439c64fe61880c90bfea0574e0f72ae1419cd7bffa016045c4e2c19"

        def install
          bin.install "tfprovidercheck"
        end
      end
    end
  end

  test do
    system "#{bin}/tfprovidercheck --version"
  end
end
