# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfprovidercheck < Formula
  desc "Censor Terraform Providers"
  homepage "https://github.com/suzuki-shunsuke/tfprovidercheck"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.1/tfprovidercheck_darwin_amd64.tar.gz"
      sha256 "b56d7866de879ada0fa78355831668ade1b2ef7ba013917bdc1c67f18af744e5"

      def install
        bin.install "tfprovidercheck"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.1/tfprovidercheck_darwin_arm64.tar.gz"
      sha256 "4e444f43865f52c1d969a9af9691f062f60e0bc64c713ee2e90c2163c8ce0d67"

      def install
        bin.install "tfprovidercheck"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.1/tfprovidercheck_linux_amd64.tar.gz"
        sha256 "44e73dbab3984f966bd6079622903c9f8bc842412171b28c5978d5fd4e0cd3cc"

        def install
          bin.install "tfprovidercheck"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.1/tfprovidercheck_linux_arm64.tar.gz"
        sha256 "2e04bbb96f952ce04c3bcbb2a04625ab9e5d371bc8c983ce6212b1951a6b302b"

        def install
          bin.install "tfprovidercheck"
        end
      end
    end
  end

  test do
    system "#{bin}/tfprovidercheck --version"
  end
end
