# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfprovidercheck" do
  desc "Censor Terraform Providers"
  homepage "https://github.com/suzuki-shunsuke/tfprovidercheck"
  version "1.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfprovidercheck"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.6/tfprovidercheck_darwin_amd64.tar.gz"
      sha256 "3a851a53dd6d1c085f532765abeaf623f7a3a669d7ba28d7dfcfdae41c22a61a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.6/tfprovidercheck_darwin_arm64.tar.gz"
      sha256 "8d2a76242564a661b22390eaec6f0da772b0737f8d1484a98769043db85125e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.6/tfprovidercheck_linux_amd64.tar.gz"
      sha256 "2520102b64cf797476b2c96f9ef285494af258c175bc945c52ae412681efc48d"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.6/tfprovidercheck_linux_arm64.tar.gz"
      sha256 "d5a545ce94091dfe625c87dd75a380f909896d92215d82d78854959955fa5fda"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfprovidercheck"]
    end
  end

  # No zap stanza required
end
