# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfprovidercheck" do
  name "tfprovidercheck"
  desc "Censor Terraform Providers"
  homepage "https://github.com/suzuki-shunsuke/tfprovidercheck"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfprovidercheck"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v#{version}/tfprovidercheck_darwin_amd64.tar.gz"
      sha256 "a72cd3322e3bca105752e43c61d7b3a88c1c7a5436451d02b45aad4afeee98bf"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v#{version}/tfprovidercheck_darwin_arm64.tar.gz"
      sha256 "c95e787c3ade838ffd03236f46c554be159e7910e0aeb80914bd726dafd762d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v#{version}/tfprovidercheck_linux_amd64.tar.gz"
      sha256 "359f87994feecdb3e5f2f53fab81ee06f793395714c17ea5e310925ea494585a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v#{version}/tfprovidercheck_linux_arm64.tar.gz"
      sha256 "809da89ab4ac255dea24a1f8dc929b6cd4fd27d61559dbf1969690f9fca45dfe"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfprovidercheck"]
    end
  end

  # No zap stanza required
end
