# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfprovidercheck" do
  desc "Censor Terraform Providers"
  homepage "https://github.com/suzuki-shunsuke/tfprovidercheck"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfprovidercheck"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.5/tfprovidercheck_darwin_amd64.tar.gz"
      sha256 "1100dde96072d5d05f1ba2b172373ea702c7a4fff253db27328b1fc688b3c0fb"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.5/tfprovidercheck_darwin_arm64.tar.gz"
      sha256 "09470000c8531d76bf3289a9534db874310346220f06439d1129be4e9b04184d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.5/tfprovidercheck_linux_amd64.tar.gz"
      sha256 "44b115e93f603b2434835830c75947a9c785fc639dd50b716ff4395d956047f1"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.5/tfprovidercheck_linux_arm64.tar.gz"
      sha256 "cb515620b53a2ce863501e7f4fee029c3a4be7c2d5e19fd37279b41f238a95aa"
    end
  end

  # No zap stanza required
end
